### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by angelkurten** [stavros0/bitcoin-price-prediction#1]
python3.5 millionaire.py

Traceback (most recent call last):
  File "millionaire.py", line 2, in <module>
    from bitcoin_price_prediction.bayesian_regression import *
ImportError: No module named 'bitcoin_price_prediction'

**Comment by stavros0** [comment]
Hi @angelkurten!

Can you tell exactly what was wrong and how to reproduce it? What's your installation process?

**Comment by angelkurten** [comment]
Hi @stavros0 run command python3.5 millonarie.py and get error:

Traceback (most recent call last):
File "millionaire.py", line 2, in 
from bitcoin_price_prediction.bayesian_regression import *
ImportError: No module named 'bitcoin_price_prediction'

¿How can I test the script?

**Comment by angelkurten** [comment]
![Image of Yaktocat](https://s11.postimg.org/co5fo2igj/Virtual_Box_Ubuntu2_25_08_2016_11_27_31.png)

**Comment by angelkurten** [comment]
![Image of Yaktocat](https://s10.postimg.org/9g7nlhii1/Virtual_Box_Ubuntu2_25_08_2016_11_31_19.png)

**Comment by stavros0** [comment]
So, the first issue was addressed? If an **ImportError exception** still arises, it's probably because of your installation process and/or your python environment. Make sure you have installed all the [prerequisites](https://github.com/stavros0/bitcoin-price-prediction#requirements) and [created an isolated Python environment](https://virtualenv.pypa.io/en/stable/) for this project (optional). Then follow the [installation instructions](https://github.com/stavros0/bitcoin-price-prediction#installation).

You don't have sufficient data to run the `millionare.py` script and therefore a **ValueError exception** arises. You need **at least** 721 data points so that [`m = len(prices) - n > 0`](https://github.com/stavros0/bitcoin-price-prediction/blob/master/bitcoin_price_prediction/bayesian_regression.py#L28). Use the `okcoin.py` script to gather more data points from the OKCoin Spot Price API and then try again. Good luck!

Bear in mind that I don't provide historical data for the time being.

**Comment by angelkurten** [comment]
@stavros0 When you run some millionarie.py result displayed on the console, I would like to talk to you by e-mail is possible?

**Comment by angelkurten** [comment]
![Image of Yaktocat](https://s11.postimg.org/af972vb0z/Virtual_Box_Ubuntu2_26_08_2016_09_38_44.png)

**Comment by stavros0** [comment]
[`millionare.py`](https://github.com/stavros0/bitcoin-price-prediction/blob/master/examples/millionaire.py) is given as an example for how to use the [`bayesian_regression.py`](https://github.com/stavros0/bitcoin-price-prediction/blob/master/bitcoin_price_prediction/bayesian_regression.py) module. It is intended for tinkering and experimenting only and therefore won't display anything on the screen. That is, you should tinker with my script or write your own script instead. In any case, you have to speak Python.

Yeah, sure. Drop me a line.

**Comment by angelkurten** [comment]
Thanks, mi e-mail is angelkurten@hotmail.com, I remain aware of your message.
